name: Main
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FORCE_COLOR: true

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-action
      - run: pnpm lint

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-action
      - run: pnpm run build

      - uses: daniel-statsig/size-limit-action@main
        if: github.event_name == 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          script: pnpm run size --json

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist/samples/web-minified'

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-action
      - run: |
          pnpm run test --testPathIgnorePatterns=MemoryLeak.test.ts
          pnpm exec nx run statsig-combo:test --testPathPattern=MemoryLeak.test.ts
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-action
      - run: pnpm exec nx run next-js-sample-e2e:e2e

  deploy:
    if: github.event_name == 'push' && github.event.repository.private
    needs: [lint, test, build]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: 'pages'
      cancel-in-progress: false
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
